//! Integration tests for v0.9 shell-primitive features (stdin auto-spool +
//! `--input` format dispatch). These spawn the release binary because
//! the spool path is fundamentally about non-seekable fds, which an
//! in-process call can't recreate cleanly.

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// Locate the freshly-built `pq` binary. We intentionally look up
/// release first (fast iteration loop) and fall back to debug — either
/// is fine for these chain assertions.
fn pq_binary() -> PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR");
    let release = PathBuf::from(manifest).join("target/release/pq");
    if release.is_file() {
        return release;
    }
    PathBuf::from(manifest).join("target/debug/pq")
}

/// Pre-canned sample.parquet path. The sample is committed-untracked but
/// regenerated by `scripts/make_sample.py` and exists in CI as part of
/// the smoke job. Local devs almost always have it from the demo.
fn sample_parquet() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("sample.parquet")
}

/// Skip the test (with a printed reason) when the prerequisites aren't on
/// disk — keeps the suite green for fresh checkouts that haven't built or
/// regenerated the sample yet.
fn skip_if_missing(p: &Path, label: &str) -> bool {
    if !p.exists() {
        eprintln!("skipping: {} not found at {}", label, p.display());
        return true;
    }
    false
}

#[test]
fn stdin_pipe_parquet_roundtrip() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    // `cat sample.parquet | pq - '.email | distinct'` — the canonical
    // case the v0.9 stdin spool exists for. Before the spool, this errored
    // out with "Cannot read parquet file: not a parquet file" because
    // duckdb couldn't seek to the footer.
    let bytes = std::fs::read(&sample).expect("read sample");
    let mut child = Command::new(&pq)
        .arg("-")
        .arg(".email | distinct")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn pq");
    child
        .stdin
        .as_mut()
        .unwrap()
        .write_all(&bytes)
        .expect("write stdin");
    let out = child.wait_with_output().expect("wait pq");
    assert!(
        out.status.success(),
        "pq failed: stderr={}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    // Exact emails come from the canned sample but at minimum we expect
    // multiple distinct rows.
    let lines: Vec<_> = stdout.lines().filter(|l| !l.is_empty()).collect();
    assert!(
        lines.len() >= 2,
        "expected >=2 distinct emails, got: {stdout}"
    );
}

#[test]
fn ndjson_chain() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    // Emits one JSON object per row from sample, pipes into a second pq
    // invocation that reads it back and reduces. Validates both:
    //   * `--input ndjson` routes to read_json with newline_delimited
    //   * stdin spool works for line-oriented formats too (DuckDB's
    //     read_json double-pass over stdin would otherwise produce 0 rows).
    let mut stage1 = Command::new(&pq)
        .arg(&sample)
        .arg(".country | to_json")
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .expect("spawn pq stage1");
    let stage1_stdout = stage1.stdout.take().expect("stage1 stdout");
    let stage2 = Command::new(&pq)
        .arg("-i")
        .arg("ndjson")
        .arg("-")
        .arg(".country | distinct | sort by .country")
        .stdin(stage1_stdout)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn pq stage2");
    let out = stage2.wait_with_output().expect("wait pq stage2");
    // Reap stage1 so clippy doesn't complain about a zombie. Status is
    // informational here — the substantive assertion is on stage2's output.
    let _ = stage1.wait();
    assert!(
        out.status.success(),
        "pq stage2 failed: stderr={}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    // The sample has US/CA/UK/DE/FR — five distinct countries.
    let n = stdout.lines().filter(|l| !l.is_empty()).count();
    assert!(n >= 4, "expected >=4 distinct rows, got {n}: {stdout}");
}
