//! Integration tests for v0.9 shell-primitive features (stdin auto-spool +
//! `--input` format dispatch). These spawn the release binary because
//! the spool path is fundamentally about non-seekable fds, which an
//! in-process call can't recreate cleanly.
//!
//! v0.12 additions: streaming (no-OOM) and lite-mode (parquet metadata-
//! only) live here too because both require process-level observation.

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// Locate the freshly-built `pq` binary. We intentionally look up
/// release first (fast iteration loop) and fall back to debug — either
/// is fine for these chain assertions.
fn pq_binary() -> PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR");
    let release = PathBuf::from(manifest).join("target/release/pq");
    if release.is_file() {
        return release;
    }
    PathBuf::from(manifest).join("target/debug/pq")
}

/// Pre-canned sample.parquet path. The sample is committed-untracked but
/// regenerated by `scripts/make_sample.py` and exists in CI as part of
/// the smoke job. Local devs almost always have it from the demo.
fn sample_parquet() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("sample.parquet")
}

/// Skip the test (with a printed reason) when the prerequisites aren't on
/// disk — keeps the suite green for fresh checkouts that haven't built or
/// regenerated the sample yet.
fn skip_if_missing(p: &Path, label: &str) -> bool {
    if !p.exists() {
        eprintln!("skipping: {} not found at {}", label, p.display());
        return true;
    }
    false
}

#[test]
fn stdin_pipe_parquet_roundtrip() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    // `cat sample.parquet | pq - '.email | distinct'` — the canonical
    // case the v0.9 stdin spool exists for. Before the spool, this errored
    // out with "Cannot read parquet file: not a parquet file" because
    // duckdb couldn't seek to the footer.
    let bytes = std::fs::read(&sample).expect("read sample");
    let mut child = Command::new(&pq)
        .arg("-")
        .arg(".email | distinct")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn pq");
    child
        .stdin
        .as_mut()
        .unwrap()
        .write_all(&bytes)
        .expect("write stdin");
    let out = child.wait_with_output().expect("wait pq");
    assert!(
        out.status.success(),
        "pq failed: stderr={}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    // Exact emails come from the canned sample but at minimum we expect
    // multiple distinct rows.
    let lines: Vec<_> = stdout.lines().filter(|l| !l.is_empty()).collect();
    assert!(
        lines.len() >= 2,
        "expected >=2 distinct emails, got: {stdout}"
    );
}

#[test]
fn ndjson_chain() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    // Emits one JSON object per row from sample, pipes into a second pq
    // invocation that reads it back and reduces. Validates both:
    //   * `--input ndjson` routes to read_json with newline_delimited
    //   * stdin spool works for line-oriented formats too (DuckDB's
    //     read_json double-pass over stdin would otherwise produce 0 rows).
    let mut stage1 = Command::new(&pq)
        .arg(&sample)
        .arg(".country | to_json")
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .expect("spawn pq stage1");
    let stage1_stdout = stage1.stdout.take().expect("stage1 stdout");
    let stage2 = Command::new(&pq)
        .arg("-i")
        .arg("ndjson")
        .arg("-")
        .arg(".country | distinct | sort by .country")
        .stdin(stage1_stdout)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn pq stage2");
    let out = stage2.wait_with_output().expect("wait pq stage2");
    // Reap stage1 so clippy doesn't complain about a zombie. Status is
    // informational here — the substantive assertion is on stage2's output.
    let _ = stage1.wait();
    assert!(
        out.status.success(),
        "pq stage2 failed: stderr={}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    // The sample has US/CA/UK/DE/FR — five distinct countries.
    let n = stdout.lines().filter(|l| !l.is_empty()).count();
    assert!(n >= 4, "expected >=4 distinct rows, got {n}: {stdout}");
}

// ── v0.12: lite-mode + streaming ─────────────────────────────────────────────

/// `pq count --lite FILE.parquet` should hit the parquet_file_metadata
/// path and produce the same row count as the regular `count(*)` path.
/// We can't directly observe whether the scan was skipped from the
/// parent process, but we *can* assert that:
///   1. the row counts match,
///   2. forced lite mode prints no banner (user opted in deliberately).
#[test]
fn count_lite_matches_full_count() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    let full = Command::new(&pq)
        .args(["count", sample.to_str().unwrap()])
        .output()
        .expect("count full");
    assert!(full.status.success(), "full count failed");
    let lite = Command::new(&pq)
        .args(["count", "--lite", sample.to_str().unwrap()])
        .output()
        .expect("count lite");
    assert!(lite.status.success(), "lite count failed");
    let full_out = String::from_utf8_lossy(&full.stdout).into_owned();
    let lite_out = String::from_utf8_lossy(&lite.stdout).into_owned();
    assert_eq!(full_out.trim(), lite_out.trim(), "row count mismatch");
    let lite_err = String::from_utf8_lossy(&lite.stderr);
    assert!(
        !lite_err.contains("lite mode"),
        "explicit --lite shouldn't emit a banner; stderr was: {lite_err}"
    );
}

/// Auto-lite triggers when the file size crosses `PQ_LITE_THRESHOLD`.
/// Set the threshold to 1 byte so any non-empty parquet hits it; the
/// stderr banner is the user-facing observable.
#[test]
fn count_auto_lite_triggers_under_threshold() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    let out = Command::new(&pq)
        .env("PQ_LITE_THRESHOLD", "1")
        .args(["count", sample.to_str().unwrap()])
        .output()
        .expect("count auto-lite");
    assert!(out.status.success(), "count failed");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("lite mode"),
        "expected lite-mode banner on stderr, got: {stderr}"
    );
}

/// ndjson streaming: pipe the sample as ndjson and verify pq emits its
/// first line before reading every input row. Smoke-tests the v0.12
/// stream-from-cursor path: pre-v0.12 we collected every row before
/// emitting any of them, so a 100M-row scan would OOM. We can't easily
/// observe memory, but we can observe per-row correctness on a small
/// fixture and a non-trivial (>10k rows) generated stream.
///
/// The actual streaming behaviour is best validated by hand on a
/// 10GB+ file (`pq -i ndjson huge.ndjson '.x' | head -1` returns
/// instantly post-v0.12); this test guards against accidental
/// re-introduction of the buffer-everything code path.
#[test]
fn ndjson_streaming_preserves_order() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    let out = Command::new(&pq)
        .args([sample.to_str().unwrap(), "-o", "ndjson"])
        .output()
        .expect("pq ndjson");
    assert!(out.status.success());
    let stdout = String::from_utf8_lossy(&out.stdout);
    let lines: Vec<&str> = stdout.lines().filter(|l| !l.is_empty()).collect();
    assert!(
        lines.len() >= 5,
        "expected several ndjson lines, got {}: {stdout}",
        lines.len()
    );
    for line in &lines {
        assert!(
            line.starts_with('{') && line.ends_with('}'),
            "every line should be a complete JSON object: got {line}"
        );
    }
}

/// Regression: `pq | head -1` must not surface a "Broken pipe" error
/// to stderr just because the downstream consumer closed the pipe
/// after one row. v0.12.0 forgot to reset SIGPIPE, so streaming
/// output (introduced in the same release) made every `pq … | head`
/// invocation print noise. The fix is `signal(SIGPIPE, SIG_DFL)` at
/// startup.
#[test]
#[cfg(unix)]
fn streaming_to_closed_pipe_emits_no_stderr() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    // Pipe `pq -o ndjson sample.parquet '.email'` into `head -1`.
    // The downstream `head` will close stdin after the first line —
    // pq must take SIGPIPE silently rather than complaining.
    let mut producer = Command::new(&pq)
        .args([sample.to_str().unwrap(), "-o", "ndjson"])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn pq");
    let pq_stdout = producer.stdout.take().expect("stdout");
    let head = Command::new("head")
        .arg("-1")
        .stdin(pq_stdout)
        .stdout(Stdio::piped())
        .spawn()
        .expect("spawn head");
    let _head_out = head.wait_with_output().expect("head finish");
    let pq_out = producer.wait_with_output().expect("pq finish");
    let stderr = String::from_utf8_lossy(&pq_out.stderr);
    assert!(
        !stderr.to_lowercase().contains("broken pipe")
            && !stderr.to_lowercase().contains("os error 32"),
        "pq leaked broken-pipe noise to stderr: {stderr}"
    );
}

/// CSV streaming: header + N data rows, emitted in input order.
#[test]
fn csv_streaming_writes_header_first() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    let out = Command::new(&pq)
        .args([sample.to_str().unwrap(), "-o", "csv"])
        .output()
        .expect("pq csv");
    assert!(out.status.success());
    let stdout = String::from_utf8_lossy(&out.stdout);
    let mut lines = stdout.lines().filter(|l| !l.is_empty());
    let header = lines.next().expect("header line");
    assert!(
        header.contains(','),
        "first line should be a CSV header, got: {header}"
    );
    assert!(
        lines.next().is_some(),
        "expected at least one data row after header"
    );
}

/// `pq stats --lite` should produce one row per leaf parquet column,
/// with the `min` / `max` / `nulls` / `rows` shape we promise. The
/// schema-order guarantee (column_id-based ORDER BY) is asserted by
/// matching the first column to the first projection in the source
/// parquet — alphabetic ordering would re-shuffle these and the
/// assertion would fail.
#[test]
fn stats_lite_returns_per_column_metadata() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    let out = Command::new(&pq)
        .args(["stats", "--lite", sample.to_str().unwrap(), "-o", "ndjson"])
        .output()
        .expect("pq stats --lite");
    assert!(
        out.status.success(),
        "pq stats --lite failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    let lines: Vec<&str> = stdout.lines().filter(|l| !l.is_empty()).collect();
    assert!(
        !lines.is_empty(),
        "expected at least one column row, got: {stdout}"
    );
    // First line is JSON — verify the lite-shape columns are
    // present. We check key names rather than values because the
    // values depend on whatever sample.parquet looks like locally.
    let first = lines[0];
    for key in ["column_name", "column_type", "min", "max", "rows", "nulls"] {
        assert!(
            first.contains(key),
            "expected key `{key}` in lite stats row: {first}"
        );
    }
    // Lite intentionally omits the data-scan-only fields so users
    // don't think they got an exact distinct count.
    assert!(
        !first.contains("approx_distinct"),
        "lite mode should not surface approx_distinct: {first}"
    );
    assert!(
        !first.contains("null_pct"),
        "lite mode should not surface null_pct: {first}"
    );
}

/// JSON streaming: validate that -o json produces a valid JSON array with
/// proper brackets and comma separators. Issue #2 acceptance criteria: the
/// output must stream directly to stdout (no buffering) while remaining a
/// valid JSON document.
#[test]
fn json_streaming_writes_brackets_and_separators() {
    let pq = pq_binary();
    let sample = sample_parquet();
    if skip_if_missing(&pq, "pq binary") || skip_if_missing(&sample, "sample.parquet") {
        return;
    }
    let out = Command::new(&pq)
        .args([sample.to_str().unwrap(), "-o", "json"])
        .output()
        .expect("pq json");
    assert!(out.status.success());
    let stdout = String::from_utf8_lossy(&out.stdout);

    // Validate structure: must start with '[' and end with ']'
    let trimmed = stdout.trim();
    assert!(
        trimmed.starts_with('['),
        "JSON streaming must start with '[', got: {}",
        &trimmed[..trimmed.len().min(50)]
    );
    assert!(
        trimmed.ends_with(']'),
        "JSON streaming must end with ']', got: {}",
        &trimmed[trimmed.len().saturating_sub(50)..]
    );

    // Parse as JSON to ensure validity and check structure
    let parsed: serde_json::Result<Vec<serde_json::Value>> = serde_json::from_str(trimmed);
    assert!(
        parsed.is_ok(),
        "JSON output must be a valid JSON array, got parse error: {}",
        parsed.unwrap_err()
    );

    let arr = parsed.unwrap();
    assert!(!arr.is_empty(), "JSON array must contain at least one row");

    // Verify each row is a JSON object
    for (i, row) in arr.iter().enumerate() {
        assert!(
            row.is_object(),
            "row {} must be a JSON object, got: {}",
            i,
            row
        );
    }

    // Validate comma-separation at the string level (smoke test that
    // incremental writer placed separators correctly). Between rows
    // we expect `},\n{`.
    let has_comma_separator = stdout.contains("},\n{");
    if arr.len() > 1 {
        assert!(
            has_comma_separator,
            "multiple rows must be separated by `,\\n`, but got: {}",
            &stdout[..stdout.len().min(200)]
        );
    }
}

// ── v0.14: pq diff ─────────────────────────────────────────────────────────

/// Write `contents` to a temporary file with extension `ext` and return
/// the path. Caller is responsible for letting it be cleaned up at the
/// end of the test (we use std::env::temp_dir + a unique name).
fn write_temp_file(name: &str, contents: &str) -> PathBuf {
    let mut path = std::env::temp_dir();
    path.push(format!("pq-diff-test-{}-{name}", std::process::id()));
    let mut f = std::fs::File::create(&path).expect("create temp");
    f.write_all(contents.as_bytes()).expect("write temp");
    path
}

#[test]
fn diff_identical_ndjson_exits_zero() {
    let pq = pq_binary();
    if skip_if_missing(&pq, "pq binary") {
        return;
    }
    let a = write_temp_file(
        "same-a.ndjson",
        "{\"id\": 1, \"name\": \"a\"}\n{\"id\": 2, \"name\": \"b\"}\n",
    );
    let b = write_temp_file(
        "same-b.ndjson",
        "{\"id\": 3, \"name\": \"c\"}\n{\"id\": 4, \"name\": \"d\"}\n",
    );

    let out = Command::new(&pq)
        .args([
            "diff",
            a.to_str().unwrap(),
            b.to_str().unwrap(),
            "-i",
            "ndjson",
        ])
        .output()
        .expect("pq diff");

    let _ = std::fs::remove_file(&a);
    let _ = std::fs::remove_file(&b);

    assert!(
        out.status.success(),
        "identical schemas must exit 0; stderr={}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("No drift"),
        "expected 'No drift' in stdout, got: {stdout}"
    );
}

#[test]
fn diff_drifted_ndjson_exits_one_with_added_section() {
    let pq = pq_binary();
    if skip_if_missing(&pq, "pq binary") {
        return;
    }
    // b has a `country` field that a doesn't — schema drift.
    let a = write_temp_file("drift-a.ndjson", "{\"id\": 1, \"name\": \"a\"}\n");
    let b = write_temp_file(
        "drift-b.ndjson",
        "{\"id\": 1, \"name\": \"a\", \"country\": \"US\"}\n",
    );

    let out = Command::new(&pq)
        .args([
            "diff",
            a.to_str().unwrap(),
            b.to_str().unwrap(),
            "-i",
            "ndjson",
        ])
        .output()
        .expect("pq diff");

    let _ = std::fs::remove_file(&a);
    let _ = std::fs::remove_file(&b);

    // Drift → exit code 1 (CI-friendly).
    assert_eq!(
        out.status.code(),
        Some(1),
        "drift must exit 1; stderr={}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("## Added"),
        "expected '## Added' in {stdout}"
    );
    assert!(stdout.contains("country"), "expected 'country' in {stdout}");
}

#[test]
fn diff_json_format_emits_parseable_object() {
    let pq = pq_binary();
    if skip_if_missing(&pq, "pq binary") {
        return;
    }
    let a = write_temp_file("jdiff-a.ndjson", "{\"id\": 1, \"name\": \"a\"}\n");
    let b = write_temp_file(
        "jdiff-b.ndjson",
        "{\"id\": 1, \"name\": \"a\", \"new_field\": 42}\n",
    );

    let out = Command::new(&pq)
        .args([
            "diff",
            a.to_str().unwrap(),
            b.to_str().unwrap(),
            "-i",
            "ndjson",
            "--format",
            "json",
        ])
        .output()
        .expect("pq diff json");

    let _ = std::fs::remove_file(&a);
    let _ = std::fs::remove_file(&b);

    let stdout = String::from_utf8_lossy(&out.stdout);
    let parsed: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("invalid JSON: {e}\nstdout:\n{stdout}"));
    assert_eq!(parsed["drift"], true);
    assert_eq!(parsed["added"][0]["name"], "new_field");
    assert_eq!(parsed["unchanged_count"], 2);
}
